from logging.config import fileConfig
from sqlalchemy import engine_from_config, pool, create_engine, String
from alembic import context
from app.config import get_settings
from app.db import Base, GUID

# Import ALL models so Alembic sees every table
from app.models import (  # noqa: F401
    user, meal_plan, recipe, grocery, gamification,
    saved_recipe, nutrition, local_food,
)

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Override sqlalchemy.url from the app settings / DATABASE_URL env var
settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.database_url)

target_metadata = Base.metadata


def render_item(type_, obj, autogen_context):
    """Render GUID as sa.String(36) in autogenerated migrations."""
    if type_ == "type" and isinstance(obj, GUID):
        return "sa.String(length=36)"
    return False


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(url=url, target_metadata=target_metadata, literal_binds=True, render_item=render_item)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    url = config.get_main_option("sqlalchemy.url")
    connect_args = {}
    if url.startswith("sqlite"):
        connect_args["check_same_thread"] = False
    connectable = create_engine(url, poolclass=pool.NullPool, connect_args=connect_args)
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata, render_item=render_item)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
