"""add metabolic budget tables

Revision ID: 101ae474f691
Revises: 236508280699
Create Date: 2026-03-01 13:02:23.849985

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '101ae474f691'
down_revision: Union[str, None] = '236508280699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metabolic_budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('protein_target_g', sa.Float(), nullable=True),
    sa.Column('fiber_floor_g', sa.Float(), nullable=True),
    sa.Column('sugar_ceiling_g', sa.Float(), nullable=True),
    sa.Column('weight_protein', sa.Float(), nullable=True),
    sa.Column('weight_fiber', sa.Float(), nullable=True),
    sa.Column('weight_sugar', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metabolic_budgets_user_id'), 'metabolic_budgets', ['user_id'], unique=True)
    op.create_table('metabolic_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_lb', sa.Float(), nullable=True),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('goal', sa.String(), nullable=True),
    sa.Column('activity_level', sa.String(), nullable=True),
    sa.Column('target_weight_lb', sa.Float(), nullable=True),
    sa.Column('protein_target_g', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metabolic_profiles_user_id'), 'metabolic_profiles', ['user_id'], unique=True)
    op.create_table('metabolic_streaks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=True),
    sa.Column('longest_streak', sa.Integer(), nullable=True),
    sa.Column('last_qualifying_date', sa.Date(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metabolic_streaks_user_id'), 'metabolic_streaks', ['user_id'], unique=True)
    op.create_table('metabolic_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('food_log_id', sa.String(length=36), nullable=True),
    sa.Column('protein_score', sa.Float(), nullable=True),
    sa.Column('fiber_score', sa.Float(), nullable=True),
    sa.Column('sugar_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['food_log_id'], ['food_logs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', 'scope', 'food_log_id', name='uq_metabolic_score_user_date_scope_log')
    )
    op.create_index(op.f('ix_metabolic_scores_date'), 'metabolic_scores', ['date'], unique=False)
    op.create_index(op.f('ix_metabolic_scores_user_id'), 'metabolic_scores', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metabolic_scores_user_id'), table_name='metabolic_scores')
    op.drop_index(op.f('ix_metabolic_scores_date'), table_name='metabolic_scores')
    op.drop_table('metabolic_scores')
    op.drop_index(op.f('ix_metabolic_streaks_user_id'), table_name='metabolic_streaks')
    op.drop_table('metabolic_streaks')
    op.drop_index(op.f('ix_metabolic_profiles_user_id'), table_name='metabolic_profiles')
    op.drop_table('metabolic_profiles')
    op.drop_index(op.f('ix_metabolic_budgets_user_id'), table_name='metabolic_budgets')
    op.drop_table('metabolic_budgets')
    # ### end Alembic commands ###
