"""add_group_mes_score_and_tier_to_food_logs

Revision ID: a852f1eae6ce
Revises: cc3804ced039
Create Date: 2026-03-03 15:09:01.558068

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a852f1eae6ce'
down_revision: Union[str, None] = 'cc3804ced039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_logs', sa.Column('group_mes_score', sa.Float(), nullable=True))
    op.add_column('food_logs', sa.Column('group_mes_tier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_logs', 'group_mes_tier')
    op.drop_column('food_logs', 'group_mes_score')
    # ### end Alembic commands ###
