"""add_group_id_to_food_logs

Revision ID: cc3804ced039
Revises: c3f8a9b21d04
Create Date: 2026-03-03 14:38:27.233107

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cc3804ced039'
down_revision: Union[str, None] = 'c3f8a9b21d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_logs', sa.Column('group_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_food_logs_group_id'), 'food_logs', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_logs_group_id'), table_name='food_logs')
    op.drop_column('food_logs', 'group_id')
    # ### end Alembic commands ###
